name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cat README.md | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt