name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user=root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cat README.md | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt