name: CI
on:
  - push
  - pull_request
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11.0.13'
      - run: mvn package
      - uses: actions/upload-artifact@v2
        with:
          name: menu-server
          path: ./target/menu-server.jar
  Unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11.0.13'
      - run: mvn test
  IT_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11.0.13'
      - run: mvn verify -DskipUnittests=true
